### ISSUE TITLE
Write tests for the DataExtensions

### ISSUE THREAD

**Issue by NightJar** [spekulatius/silverstripe-composer-security-checker#35]
Integration tests more than unit, however the module currently has support for the `silverstripe-maintenance` module iff it is installed, but does not test this.

Usage of `setUpOnce`/`setUp` to test if the `bringyourownideas/silverstripe-maintenance` module exists, and using `$this->markTestSkipped('Maintenance module not present')` would see us able to use some fixtures and test various points of the extensions, such as whether or not the appropriate asset files are included (css,js), outputs are modified, etc.

- [x] This assumes #34 will be merged first.

**Comment by robbieaverill** [comment]
There's a bunch of situations where we've got extra modules installed in some CI build situations (like adding in subsites or queuedjobs) - would be good to add it for some but not all matrix entries, and ensure that if you're skipping tests that don't have a module present that you'd run code coverage on the run that has the least number of tests skipped =)
