### ISSUE TITLE
Handle the closure of security.sensiolabs.org

### ISSUE THREAD

**Issue by ScopeyNZ** [spekulatius/silverstripe-composer-security-checker#44]
Apparently [security.sensiolabs.org](//security.sensiolabs.org) will be shutting down at the end of October. Considering that's the day after tomorrow we should probably design a solution that works with Symfony's new paid service: [security.symfony.com](//security.symfony.com) .

There miiight be a way to get some sort of open source allowance if we ask nicely considering the money apparently goes to open source projects?

**Comment by be2n** [comment]
Thanks, @ScopeyNZ  - yes, let's get onto replacing sensiolabs.

**Comment by brynwhyman** [comment]
This can be closed. The service is staying open sourced. We just need to bump to the new version of `sensiolabs/security-checker` in this module.

See #45
