### ISSUE TITLE
Bump sensiolabs/security-checker to ^5 for v1 and v2

### ISSUE THREAD

**Issue by brynwhyman** [spekulatius/silverstripe-composer-security-checker#45]
Contrary to #44 , the security-checker CLI too will stay open source.

With the closure of security.sensiolabs.org the endpoint used by `sensiolabs/security-checker` has changed to security.symfony.com in version 5 of the tool.

**Comment by brynwhyman** [comment]
Could be a change/major if we're bumping the dependancy to a new major?

**Comment by robbieaverill** [comment]
Fixed in #46

**Comment by robbieaverill** [comment]
@brynwhyman we don't expose any of that dependencies API as part of the public API of this package, so in essence we haven't changed any of this module's API, therefore it should be OK as a patch fix (IMO)
