### ISSUE TITLE
Queue the buildtask when the maintenance module runs 'Check for updates'

### ISSUE THREAD

**Issue by brynwhyman** [spekulatius/silverstripe-composer-security-checker#52]
## Overview
The information served through this module is most useful when paired with the [Silverstripe maintenance module](https://github.com/bringyourownideas/silverstripe-maintenance), however without a Developer setting up a scheduled process (e.g `cron`) to run the buildtask, or someone manually running it via a queuedjob, security advisories are not readily available to CMS users in the report.

I'm suggesting an enhancement where, if the silverstripe-maintenance module report is installed along side this module, the 'Check for updates' button in the maintenance report also schedules and runs the the security-checker buildtask.

## Acceptance criteria
- [ ] The 'Check for updates' button in the maintenance report queues the `SecurityAlertCheckTask` via a queuedjob
- [ ] Other jobs already queued with the 'Check for updates' button in the maintenance report remain
- [ ] This feature is documented in the this module's readme, and the maintenance report's readme as a suggestion
- [ ] The maintenance report userhelp documentation is update to reference this as a feature

## Notes

The buildtask has been reported to currently be broken when run via a queuedjob. PR to resolve that is here: https://github.com/bringyourownideas/silverstripe-composer-security-checker/pull/51

**Comment by spekulatius** [comment]
Hello @brynwhyman,

again sorry for the slow responses. I'm overseas and fighting hardware issues while being in a locked-down country at the same time.

The idea to allow for a manual triggered update sounds good - this would enhance the user experience IMHO. Do you think you want to get started on PR for this? I'm pretty limited in time and internet access - can't contribute much at this point due to a broken laptop.

Cheers,
Peter

**Comment by brynwhyman** [comment]
Hey @spekulatius at this stage I'm not sure when we might get to this either. However I think it would provide a lot of value to people using the report so I'll see if I can rally some people to help over the next couple of months (unless someone else beats me to it! 😄 )

**Comment by robbieaverill** [comment]
Description says it’s resolved now, can we close?

**Comment by brynwhyman** [comment]
@robbieaverill #51 fixed the issue where the buildtask would just fail when run via queued jobs. 

We still want to have the maintenance module queue this buildtask directly from the 'installed modules report' - which this issue covers. 

I've updated the description to make that a little more clear.

**Comment by spekulatius** [comment]
Yeah, fair enough. Any support you can find is appreciated.`

**Comment by brynwhyman** [comment]
Given this module[ is being abandoned](https://github.com/bringyourownideas/silverstripe-composer-security-checker#readme), closing this.
